### ISSUE TITLE
The requested module '@nanoexpress/*' does not provide an export named 'default'

### ISSUE THREAD

**Issue by torbjorn-kvist** [nanoexpress/middlewares#13]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo
https://github.com/torbjorn-kvist/nanoexpress-default-import
`npm i && npm start`

### Current Behavior
`import schemator from '@nanoexpress/middleware-schemator'`
results in error message
````
nanoexpress-default-import/src/simple-doc.js:5
import schemator from '@nanoexpress/middleware-schemator'
       ^^^^^^^^^
SyntaxError: The requested module '@nanoexpress/middleware-schemator' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nanoexpress-default-import@1.0.0 start: `node src/simple-doc.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nanoexpress-default-import@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/torbjorn/.npm/_logs/2021-01-03T09_43_53_627Z-debug.log
````
The same happens for 
```
import staticServe from '@nanoexpress/middleware-static-serve'
import bodyParser from '@nanoexpress/middleware-body-parser'
```
### Expected behavior/code
Getting access to imported object and that the server will start on port `4000`

### Environment
- Node/npm version: v14.15.3 / 6.14.9
- OS:  Debian GNU/Linux 10 (buster)

### Note
Only tested this on the three middlewares mention above, so it could be the same problem on the other modules when using ESM.

**Comment by torbjorn-kvist** [comment]
it seems that it can be fixed by doing this: 
https://github.com/torbjorn-kvist/middlewares/commit/db7fd3c67d63d22d35a624c9bca11b651ab80f09

Not sure how to test it without publishing an npm package, tried to do a .tgz with npm pack but was not allowed to installed. But tried to do the same changes in `node_modules`. 

When doing these changes it works, also need to the same change in https://github.com/dalisoft/npm-packages/tree/master/packages/getdirname because `schemator` is using it. 

It works if you import the packages as '@nanoexpress/middleware-schemator/module' but then I'm getting the same error for `getdirname`. 

Not sure how you want to solve this, but it seems to work with the current changes on the fork.

**Comment by dalisoft** [comment]
@torbjorn-kvist Can you make PR for this? If possible with tests please, i'll fix this as soon as i can, but seems it's not current month, at next month i think i can do. If you need faster result, please submit PR

**Comment by torbjorn-kvist** [comment]
Can make a PR for it, but not sure how to test without another repository importing it from package.json. Will try to look into both when I get some time over.

**Comment by torbjorn-kvist** [comment]
@dalisoft b0e7e4b16e51eec22365e69f21a7b8490eb77ea6 solved it for body-parser. Nice!

**Comment by dalisoft** [comment]
@torbjorn-kvist Please test it on both ESM and CJS mode and let me know results

**Comment by cryptodeal** [comment]
@dalisoft I was able to test body-parser on both ESM and CJS and can confirm both modes are working!

**Comment by dalisoft** [comment]
Thanks @cryptodeal 
I also tested body-parser and it works, but i am stuck with schemator plugin solution for getdirname dependency.

**Comment by dalisoft** [comment]
Only `schemator` has bug with CJS as it's has dependency called `getdirname`, once i'll fix that dependency, `schemator` also will be able use full-compatible Node.js power

**Comment by dalisoft** [comment]
Commit 0ca4a3e34bd0cc16f6e806e9c81581d619c4b982 fixes this issue completely (or should fix at least)
