### ISSUE TITLE
file-upload middleware

### ISSUE THREAD

**Issue by harshmandan** [nanoexpress/middlewares#14]
## Feature Request

Hi, What about a file upload middleware?

**Comment by dalisoft** [comment]
@harshmandan Hi and thanks for interesting. Currently i don't have enough time, i have plans adding few more middlewares to make this project better and flexible

**Comment by dalisoft** [comment]
I try do it in next month, until it you can use express-upload, i will do fastest uploading mechanism with a lot of flexibility, but currently i don't have time, you can help me by writing articles, sharing project, Star, Fork or creating PR.
Soon i planning remove sponsorship, so don't support project please for future development, just help by doing something.

I hop you understand me

**Comment by dalisoft** [comment]
@harshmandan High-performance file-upload now lives [here](https://github.com/nanoexpress/middlewares/tree/master/packages/file-upload). Thanks for your patience
